-- ALTERAÇÃO NA TABELA ENDERECO:
-- 	DESC: 
-- 	 - AUMENTO DO TAMANHO DA COLUNA

ALTER TABLE `tb_endereco` CHANGE `bairro` `bairro` VARCHAR(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;


-- ALTERAÇÃO NA TABELA CONFIGURAÇÃO DE QUADRO DE HORÁRIO:
-- 	DESC: 
-- 	 - A COLUNA PASSA A PERMITIR SER NULL

ALTER TABLE `tb_config_quadro_horario` CHANGE `intervalo` `intervalo` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;